require 'json'
require 'net/http'

# The vocabulary every record here answers in, and the Active Support it brings along. Two
# more files of it: an address is sent without the fields a caller left blank, and a window
# with no end reaches a year out.
require 'company'
require 'active_support/core_ext/enumerable'
require 'active_support/core_ext/integer/time'

require 'graphql/error'
require 'graphql/unauthorized'
require 'graphql/throttled'
require 'graphql/client'

require 'jbr/version'
require 'jbr/error'
require 'jbr/errors/refused'
require 'jbr/errors/throttled'
require 'jbr/token'
require 'jbr/refreshing'
require 'jbr/querying'
require 'jbr/authorizing'
require 'jbr/mock'

# Phone before Customer, and Location before Customers: what each asks Jobber for is built as
# it loads. Every record before the collection that reads it, for the same reason.
require 'jbr/phone'
require 'jbr/resources/customer'
require 'jbr/resources/location'
require 'jbr/resources/line'
require 'jbr/resources/job'
require 'jbr/resources/technician'
require 'jbr/resources/visit'
require 'jbr/resources/quote'
require 'jbr/resources/invoice'
require 'jbr/resources/lead'

require 'jbr/reader'
require 'jbr/reading'
require 'jbr/collection'
require 'jbr/includable'
require 'jbr/listable'
require 'jbr/collections/jobs'
require 'jbr/collections/visits'
require 'jbr/collections/technicians'
require 'jbr/collections/quotes'
require 'jbr/collections/invoices'
require 'jbr/collections/customers'
require 'jbr/collections/locations'
require 'jbr/collections/leads'
require 'jbr/account'

require 'jbr/mock/jobs'
require 'jbr/mock/visit'
require 'jbr/mock/visits'
require 'jbr/mock/technicians'
require 'jbr/mock/quote'
require 'jbr/mock/quotes'
require 'jbr/mock/invoice'
require 'jbr/mock/invoices'
require 'jbr/mock/leads'
require 'jbr/mock/account'

require 'jbr/event'
